#!/bin/bash
# This code is intended to squat on the same name space as the touch command and seamlessly log the action taken by the user.

REAL_TOUCH="/usr/bin/touch"
CURRENT_USER="${USER:-$(id -un)}"
FILTER_DIR="/n/netscratch"

for file in "$@"
do
  if [[ ${file::1} != "-" ]];
  then
    fullpath=$(realpath ${file})
    if [[ $fullpath == ${FILTER_DIR}* ]];
    then
      echo "${CURRENT_USER} is running touch on ${fullpath}"
    fi
  fi
done

exec "$REAL_TOUCH" "$@"
